### ISSUE TITLE
When `disable_indexing` set as true, still checks all object attributes in callbacks

### ISSUE THREAD

**Issue by mcivorsteiner** [algolia/algoliasearch-rails#101]
I have an attribute being indexed that is a method on the object that makes a call to another service.  We have it set up so indexing is disabled in test env, but even when disabled, every attribute is being checked in the callbacks, thus hitting an external service every time an object is created or updated in test env.  We use FactoryGirl and have current work around where we are disabling all the algolia callbacks in the factory definition.

Bottom line is that the disable_indexing option should disable the callbacks from being set, or at least disable the attribute checking done in the callbacks.

```
algoliasearch if: :searchable, per_environment: true, enqueue: :trigger_reindexing, disable_indexing: ENV['ALGOLIA_INDEXING_DISABLED'] do
  attribute :display_id, :name, :details, :highlights, :available_dates_unix

  attributesToIndex ['unordered(name)', 'unordered(details)', 'unordered(highlights)']
  numericAttributesToIndex ['available_dates_unix']
end

def available_dates_unix
  availability_data = Availability::Fetcher.new(self).availability_data
  availability_data.days.map { |day| Time.parse(day.date).to_i }
end
```

**Comment by ralphie02** [comment]
I am seeing a similar issue, if it's completely unrelated, please let me know. I'll create a new issue with more details if time permits.

I originally have algolia indexing enabled for production/staging/production and disabled for test environment. This works fine in most cases in rspec (or so I thought). Afterward, I added an after_commit callback when a record is created, which in turn triggers a background job to update an association that calls algolia indexing. This works fine in development/production but not in test.

Upon further investigation, it seems like the background job triggers algolia to reindex, which shouldn't happen since I have `algoliasearch_options = { disable_indexing: Rails.env.test? }`

To me, it seems like it's an issue with the background job and algolia indexing.

Hope this helps a bit.

**Comment by redox** [comment]
Hmmm, thank you for the detailed bug report @ralphie02; I'll check what's going on.
