### ISSUE TITLE
`.reindex` call is making a call to an unexpected index name

### ISSUE THREAD

**Issue by mmhan** [algolia/algoliasearch-rails#120]
Steps to reproduce:

Call `Post.reindex` in `rails console`

My expectation: 
- It would reindex all Post with environment suffix to an index named `Post_production`
- It wouldn't produce any error.

Actual:
- It reindexed all Post with environment suffix to an index named `Post_production`
- It produced an error.

```
[algoliasearch-rails] Cannot GET to https://XXXXXX-dsn.algolia.net/1/indexes/Post_production.tmp/settings: {"message":"Index does not exist","status":404} (404)
```

I wonder if it's a bug of `algoliasearch-rails` gem that somehow was looking for additional index with `.tmp` or if it's something isolated just for my case. 

As an aside: what's the difference between `Post.reindex` and `Post.reindex!`? In the library's code they are two different methods, but the difference isn't actually documented.

**Comment by redox** [comment]
> It produced an error.

Yeah, that's actually a side-effect of the logging mechanism; we call `get_settings` on this non-existing-yet temporary index; I fixed it yesterday in https://github.com/algolia/algoliasearch-rails/commit/52a19a8b6f03b4cde3fd56d2c87ac3b560b02c1f; will be part of the next release.

**Comment by redox** [comment]
> As an aside: what's the difference between Post.reindex and Post.reindex!

 * `Post.reindex!` will reindex everything using the same index
 * `Post.reindex` will reindex everything in a temporary index, and then move the temporary index over the destination index -> this is atomically done.

The drawbacks of the using `Post.reindex!` are:
 - objects that have been deleted from the DB won't be removed from the index
 - you may have inconsistencies because all the records won't be updated atomically

The drawback of the using `Post.reindex` is:
 - you'll consume twice the number of records during a few seconds/minutes

**Comment by mmhan** [comment]
That's awesome. Thanks!
