### ISSUE TITLE
Multiple indexes?

### ISSUE THREAD

**Issue by 9mm** [algolia/algoliasearch-rails#138]
I have a SAAS app where each client/customer needs their own index (so basically multiple indexes of the same model).

Imagine each paying client has their own index of many `Book` records. This model `belongs_to :company` so that each company gets their own database of books.

Basically I want to create 1 index per company using this Rails gem on the `Book` model.

How might I go about doing this? I see a few issues that might be tricky:

- Creating the appropriate index name (easiest would be to prefix the book index with the `company_id`), so... `1_Book`, `2_Book`, etc.
- Updating the appropriate index when a record is saved

Associated attributes are already taken care of properly simply because it pulls the association properly.

Searching the right index is easy, based on just the UI.

Thanks!

**Comment by redox** [comment]
Hi @9mm,

having multiple indices is definitely an option to handle such a multi-tenant SAAS app but it actually slows down the indexing time (because we need to build N indices). Also, it's indeed not something supported by our Rails integration for now. There is actually a better approach: keeping both indexing time low & security.

Instead of having 1 index per company, I would recommend you going for 1 single index for ALL companies and tag all records with their `company_id`. At search-time, you would then use our [Secured API key](https://www.algolia.com/doc/guides/security/api-keys#secured-api-keys) to restrict the search to only what a company has access to.

So a record will look like:

```json
{
  "objectID": "42",
  "name": "My book",
  [...]
  "_tags": ["company_1"]
}
```

And at query time, you will generate an API key that is only able to search for records tagged with such company ID. The resulting API key can then be used in your JS frontend code.

```ruby
public_key = Algolia.generate_secured_api_key('SearchOnlyAPIKeyKeptPrivate', {filters: 'company_1'})
```

What do you think about that?

**Comment by 9mm** [comment]
Ah interesting, that also works quite nice then.

2 fast questions, if you wouldnt mind!

1. What is the main difference between adding a `_tag` vs making it a property on the object like `company_id`? Can a filter only apply to a `tag` but not a regular property? Are there any other differences?

2. Thats the Algolia-preferred way to update associations? (See example below). I've added in `_tags` too per your suggestion.

```
  algoliasearch per_environment: true do
    attribute :year, :price
    attribute(:author){ author.full_name }

    tags do
      ["company_#{company.id}"]
    end
  end
```

Even though I have no direct index for `Author` (I dont ever need to search them directly), how can I make sure that when I edit an `Author`, those specific records could be re-indexed?

Thanks so much for your help.

**Comment by redox** [comment]
Cool :)

> What is the main difference between adding a _tag vs making it a property on the object like company_id? Can a filter only apply to a tag but not a regular property? Are there any other differences?

Tag are designed for filtering only. It could be done using a regular attribute + facet filters, but it would we slightly less efficient.

> Whats the Algolia-preferred way to update associations? (See example below). I've added in _tags too per your suggestion.

Yeah, that's something we need to work on because we don't have a strong answer. I think we should be able to reindex the parent object on touch like described in #74. In the meantime, I think the easiest is to trigger the `Book` indexing creating an `after_save` callback on the `Author`.

If you want to work on #74, I would love to merge your contribution 👍

**Comment by 9mm** [comment]
Ahh.. this makes sense. I'll keep that in mind, thanks again for your help!

**Comment by redox** [comment]
> Ahh.. this makes sense. I'll keep that in mind, thanks again for your help!

👍 You're welcome 💯

**Comment by 9mm** [comment]
One thing I just thought of...

Is it possible to load facets/facet counts based on a tag?

**Comment by 9mm** [comment]
Nevermind, this is possible just did some testing... sweet.
