### ISSUE TITLE
Algolia external service is being called even in a simple GET request

### ISSUE THREAD

**Issue by augustosamame** [algolia/algoliasearch-rails#219]
Hi. When I use my API along with the Algolia gem, I'm getting some unnecessary calls to the Algolia external service. For example a simple

`GET user?id=1`

to my API is calling Algolia even when there are no updates / deletes on the user model.

My (partial) user model:

```
class User < ActiveRecord::Base
  mount_uploader :image, AvatarUploader

  include AlgoliaSearch

  algoliasearch per_environment: true, if: :active_and_visible? do
    attribute :id
    attribute :search_name do
      self.name.blank? ? "#{self.first_name} #{self.last_name}" : self.name
    end
    attribute :search_object do
      self.is_charity ? "Charity" : "User"
    end
    add_attribute :image_thumb_search
    searchableAttributes ['search_name']
    customRanking ['desc(friend_count)']
  end

  #this will detect if first or last names have changes in the db and update full name accordingly in algolia index
  def search_name_changed?
    name_changed? || first_name_changed? || last_name_changed?
  end

  def active_and_visible?
    self.status == "active" ## && self.visible
  end

  def image_thumb_search
    self.image.thumb.url
  end

end
```

My user show controller

  ```
def show
    @user = User.find(params[:id])
    render json: @user, root: 'data', adapter: :json
  end

```

With internet access turned off, I'm getting these warnings in the call, and the call is slow:

`
[algoliasearch-rails] Cannot reach any host: getaddrinfo: nodename nor servname provided, or not known (OQFHUPHQU7.algolia.net:443), getaddrinfo: nodename nor servname provided, or not known (OQFHUPHQU7-2.algolianet.com:443), getaddrinfo: nodename nor servname provided, or not known (OQFHUPHQU7-1.algolianet.com:443), getaddrinfo: nodename nor servname provided, or not known (OQFHUPHQU7-3.algolianet.com:443)
`

Any help is appreciated to help debugging this

**Comment by redox** [comment]
Hey @augustosamame,

that's unfortunately an expected behaviour because of your `if: :active_and_visible?` condition: the gem has no way to understand whether this option was `true` before and now `false` or the opposite -> therefore we force the indexing & the removal at every single save, even if none of the attributes defined in the `algoliasearch` block have been updated.

What I recommend you is to define `_changed?` method, to help the `gem` understand if you `active_and_visible` (you'll need to remove the `?`...) has changed:

```ruby
  algoliasearch per_environment: true, if: :active_and_visible do
    # [...]
  end

  def active_and_visible
    status == "active" && visible
  end

  def active_and_visible_changed? # the gem is looking for a method with the same name, suffixed by `_changed?`
    status_changed? && visible_changed?
  end
```

You can also refer to the [note](https://github.com/algolia/algoliasearch-rails#restrict-indexing-to-a-subset-of-your-data) in our README.

Let us know how that goes!
