### ISSUE TITLE
Which API_KEY?

### ISSUE THREAD

**Issue by Spone** [algolia/algoliasearch-rails#245]
Hello,

> Create a new file config/initializers/algoliasearch.rb to setup your APPLICATION_ID and API_KEY.

when reading the documentation, it's a bit unclear which `API_KEY` I should use: `Search-Only API Key` or `Admin API Key`.

I guessed it's the Admin one if I want to be able to index data, but I think the README could be clearer on this point.

**Comment by Glioburd** [comment]
Same question here, also I noticed I don't have the same API types between two apps.
One has :

- Search-Only API Key
- Admin API Key

The other has :
- Search API Key
- Write API Key
- Admin API Key

**Comment by redox** [comment]
Sorry for the late reply @Spone & @Glioburd. Because the API key of your Rails application will never reach the frontend and will be kept privately on your server; it's OK to use the Admin API key (does read, write and admin operations) -> the search API key won't work anyway for all indexing tasks.

The difference @Glioburd spot is when you're invited to collaborate on an app. In such case we do generate a read and a write API key; in your case you've also be granted the Admin key.

Let us know if that's clear!

**Comment by Spone** [comment]
Yes, it's clear but I think you should update the documentation to make it clearer that the `API_KEY` will be used for indexing only. In my case I also want to perform searches on the front-end, so I will also store my search-only key in the ENV variables.

**Comment by Glioburd** [comment]
@redox Oh all right. Thanks for the answer!
