### ISSUE TITLE
Clarifying reindex for a shared index

### ISSUE THREAD

**Issue by oyeanuj** [algolia/algoliasearch-rails#281]
Hi @redox @raphi, quick question - what is the best way to reindex an index that is shared across models? I tried following the [instructions here](https://github.com/algolia/algoliasearch-rails#indexing) but that ends up indexing only the last model and deleting other models that were part of that index.

My current workaround is to do the following:
```rb
# Assuming Plant and Animal share the same index
Plant.index_objects Plant.all
Animal.index_objects Animal.all
```

Is there a better way of doing it so that it only updates what has changed, adds what is new and doesn't delete any of the older objects?

Thank you!

**Comment by raphi** [comment]
Hi @oyeanuj 

We do support an index for several models - see the [documentation here](https://github.com/algolia/algoliasearch-rails#share-a-single-index).
However, be careful and use `reindex!` instead of `reindex` (see docs for further details).

> Is there a better way of doing it so that it only updates what has changed, adds what is new and doesn't delete any of the older objects?

That's a different thing than a `redindexing` operation though. For that, you should let the [`auto-indexing` on](https://www.algolia.com/doc/api-client/rails/options/?language=rails#auto-indexing--asynchronism) and by default, any new / delete / change in your objects will be reflected in your index as well.

**Comment by oyeanuj** [comment]
@raphi To clarify, I was able to set up an index with multiple models. But as I tweak and test both our data and our search, I need to run batch indexing. In that case, reindexing seems like the solution.

So, are you suggesting if I use `reindex!` instead of `reindex` in the below, it should suffice for my usecase?

```rb
Rails.application.eager_load! # Ensure all models are loaded (required in development).
algolia_models = ActiveRecord::Base.descendants.select{ |model| model.respond_to?(:reindex!) }
algolia_models.each(&:reindex!)  # instead of reindex
```

Thanks!

**Comment by raphi** [comment]
@oyeanuj yes that's correct! Let me know if that works.
