### ISSUE TITLE
Algoliasearch-Rails appears to set timestamps to strings in Algolia

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-rails#292]
This was shocking to me upon reading https://www.algolia.com/doc/guides/indexing/formatting-your-data/:

> # Dates
> 
>  Date attributes should be formatted as Unix Timestamps (ex. 1435735848) if you want to filter, or sort by date. By default the Algolia engine doesn’t interpret strings following the ISO date format, so you must convert your dates into numeric values. 

since this first-party library appears to do the wrong thing when running

```ruby
  algoliasearch do
    attribute :created_at 
  end
```

Here, `created_at` ends up as a string in Algolia. I believe this to be an insane and costly default to have - I now have to go and carefully reindex my whole database and swap out client code at the same time.

**Comment by redox** [comment]
Unfortunately, this is more an issue of the JSON format: not supporting Date/Time formats.

In order to avoid do anything automatically (we don't want our libraries or engine to act as blackboxes), we decided to not apply any transformation on the way we format attributes. In this case, we let the regular Ruby JSON serializer apply its own logic: which is indeed converting this datetime to an ISO string (in ruby).

If you want this date to be used for sorting purposes, I recommend doing:

```ruby
  algoliasearch do
    attribute :created_at_i do
       self.created_at.to_i
    end
  end
```

**Comment by vincentwoo** [comment]
Ehh... the point of using the rails library instead of the ruby library *is* to do this kind of stuff automatically.

**Comment by redox** [comment]
> Ehh... the point of using the rails library instead of the ruby library is to do this kind of stuff automatically.

The main goal is first to handle the models lifecycle (auto indexing relying on Rails' callbacks); then indeed we could provide this or that date helpers for convenience but I don't think we want to always convert times to timestamps; plus we would have an issue with dates (that you cannot really convert to timestamp because of unknown timezone)...

Because the required code to get there is straight-forward, I don't think we'll add a helper for "time".

Does that make sense @vincentwoo?

**Comment by vincentwoo** [comment]
at minimum a format like `attribute :date, :int` would be useful for automatic type conversion. defaulting to json's behavior seems like a really strange choice. why json? it has nothing to do with the algolia-specific protocol.

**Comment by redox** [comment]
> at minimum a format like attribute :date, :int would be useful for automatic type conversion. defaulting to json's behavior seems like a really strange choice.

Yes, definitely good insights for the v2 (we're thinking about rewriting the library from scratch in the next few months).

> why json? it has nothing to do with the algolia-specific protocol.

Algolia uses JSON to format the records, not sure I got your message.

**Comment by vincentwoo** [comment]
Algolia's use of the JSON serialization protocol to receive or respond to requests should have very little to do with the default behavior of the Rails gem. The purpose of the gem should be to *abstract away* any protocol details from the user.

**Comment by david-mears-dfe** [comment]
Thanks for creating this issue.

For future readers or gem developers, note that in Ruby `nil.to_i` evaluates as 0, which might not be what you want for null date/time attributes.
