### ISSUE TITLE
Warning ruby 2.7

### ISSUE THREAD

**Issue by fabdbt** [algolia/algoliasearch-rails#376]
- Ruby version: 2.7.0
- Rails version: 6.0.2.1
- Algolia Rails integration version: 1.23.2
- Algolia Client Version: 1.27.1
- Language Version: French

### Description

```sh
/usr/local/bundle/ruby/2.7.0/gems/algoliasearch-rails-1.23.2/lib/algoliasearch-rails.rb:392: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

### Steps To Reproduce

Start a Rails fresh project using ruby 2.7 and rails 6.0.2.1. Include gem `algoliasearch-rails` and run `bundle exec rails s`.

**Comment by vvo** [comment]
@Apokly Thanks! This might be easier than you think to fix this by yourself and submit a PR. Here's an example PR that fixed it in another library, see: https://github.com/lostisland/faraday/pull/1009/files

Can you give it a try? Thanks!

**Comment by ukd1** [comment]
Also having this issue - is this gem maintained?

**Comment by chloelbn** [comment]
Hey @fabdbt and @ukd1! First of all thanks a lot for your contribution and your question. This gem is still maintained but for the moment, because of limited resources on our side, reviews and new features are on hold. A Ruby client v2 is however on its way 🎉 and with that new client we'll be able to make a better Rails integration as well. Thank you for your patience!

**Comment by ukd1** [comment]
@chloelbn we pay you a lot for algolia, and your code is interrupting us all the time now. Please fix this; it’s very simple, but we don’t want to fork to fix this. It’s not acceptable to me that your code throws a warnings on a current ruby version.

**Comment by ain** [comment]
Calling for a faster Code Review as well. 

@chloelbn it's only fair that you prioritise reviewing contributions from the community esp. if it's not a feature but a deprecation warning affecting all users using the gem. It has been open since January!

Should make a very easy and fast patch release.

**Comment by chloelbn** [comment]
Hi @ain @fabdbt @ukd1,
The fix has been merged and we will deploy it shortly. Thanks again for your patience, we did our best to handle this problem as fast as we could with our limited resources. It's valuable that you pinged us multiple times so we could indeed prioritize it! Don't hesitate either to reach us through support@algolia.com as well when you face issues, as it helps us link them to your account and understand better your use-case and problems.
Have a good day,
