### ISSUE TITLE
Silly question...

### ISSUE THREAD

**Issue by 9mm** [algolia/algoliasearch-rails#45]
What is the best way to not affect my production database when developing locally? Do I need to create a whole new application? Or do I create a new indice with the same name (Post)?

Lastly, is there a special dev mode where it won't count against my usage?

**Comment by redox** [comment]
The easiest is to use the `per_environment` (https://github.com/algolia/algoliasearch-rails#per-environment-indexes) option to suffix your index with the current environment. You can even generate some API keys that are only targeting "*_development" or "*_test" to ensure your "*_production" indices will never be impacted.

Since a few days, we've released the ability to create multiple applications (https://www.algolia.com/applications) -> you could also create a new app to have a dedicated application_id/api_key for your development.

I'm closing this issue; feel free to comment if you need more details!

**Comment by 9mm** [comment]
Perfect! Thanks so much, I totally didn't even see that option.

By the way, this is unrelated but I think Algolia is one of the coolest, well-put-together and truly amazing SAAS companies I've seen/used in a long, long, LONG time. I am not really one to gawk over stuff like that, but Algolia is just amazing. From the ease and intuitiveness of the ruby gem, your documentation, your website, your beautifully designed backend, your stunningly fast speed, your fair pricing... I was just telling a few people there needs to be more companies like this. You guys solved a real world problem that I have had for so long in such a crazy awesome way. Keep it up.

**Comment by redox** [comment]
Thank you very much for the positive feedback, we really appreciate :+1:  :zap:
