### ISSUE TITLE
Several model for the same index

### ISSUE THREAD

**Issue by cbou** [algolia/algoliasearch-rails#46]
It's not an issue but a question. I post it here because maybe some people are interested in the response.

Is it possible to have one index used for multiple models? I'm sure indexing should work but what about double id (same in model A and model B) and searching?

Do I need to first copy A and B in a model C by myself and then index C in Algolia?

**Comment by redox** [comment]
Hi @cbou,

posting the question here is a very good idea!

The "multiple models to single index" is actually not the use-case the gem has been designed for. That being said, since you can override the `objectID` using the `:id =>` option and if you ensure that you set the same index settings (through the `algoliasearch` block) in all models (otherwise the gem will continuously try to setSettings because the applied one are not matching the model configuration); it *should* work.

Do you mind giving it a try?

**Comment by cbou** [comment]
Ok inserting could work this way, I will try.

Is there no easy way to search with rails and get the results automatically convert into model objects?

**Comment by redox** [comment]
Hmmmm; I generally recommend to use `raw_search` and deal with the JSON raw answer.

**Comment by cbou** [comment]
Actually I will stick with a third class for other reasons. I just post the solution I started to implement:

Class A and B:
```ruby
  algoliasearch index_name: "records", id: :index_id do
    attribute :name
  end
  def index_id
    "A-#{id}" # "B-#{id}" for Class B
  end
```

Then you can override AlgoliaSearch like that:

```ruby
module AlgoliaSearch::ClassMethods
   def search(q, params = {})
     # Override search to either instantiate class A or B after a raw_search.
     # Just copy search from lib/algoliasearch-rails.rb from this repository.
   end
end
```

Actually pretty easy
