### ISSUE TITLE
Access Analytics API

### ISSUE THREAD

**Issue by kitwalker12** [algolia/algoliasearch-rails#47]
can I access the analytics rest endpoints (https://www.algolia.com/doc/rest_api#SectionAnalytics) like popular searches from the client?

**Comment by redox** [comment]
No the Analytics API is not usable from our search API clients; they have been designed for the search only. The Analytics API is actually using different hostname (```analytics.algolia.com``` instead of ```APP_ID-{1,2,3}.algolia.net```) so it makes probably more sense to create dedicated projects for it.

I recommend to use a simple `RestClient` instance here, should do the job.

Closing the issue, but let me know if you need more details!

**Comment by kitwalker12** [comment]
something like this would do then https://gist.github.com/kitwalker12/d5f4f896f56a9e2951a3

**Comment by redox** [comment]
Yep, definitely. We recommend using "algolia.net" instead of "algolia.io" but looks good :)
