### ISSUE TITLE
Configuration Initializer with secrets

### ISSUE THREAD

**Issue by StephaneJuban** [algolia/algoliasearch-rails#88]
Is it possible to do the configuration with secrets ?
`AlgoliaSearch.configuration = { application_id: Rails.application.secrets.YourApplicationID, api_key: Rails.application.secrets.YourAPIKey }`

When I do that, a error is raised when I do `bundle exec rake db:schema:load`
`ArgumentError: No APPLICATION_ID provided, please set :application_id`

I'm using an ugly workaround for now.

Thanks

**Comment by redox** [comment]
That should work, are you sure `Rails.application.secrets.YourApplicationID` is defined? I'm used to use [figaro](https://github.com/laserlemon/figaro) with `AlgoliaSearch.configuration = { application_id: ENV['ALGOLIA_APPLICATION_ID'], api_key: ENV['ALGOLIA_API_KEY'] }` and it works well.

I'm closing the issue because it doesn't seem to be a gem bug; feel free to re-open it if you have more details.
