### ISSUE TITLE
disjunctive facets?

### ISSUE THREAD

**Issue by AlexGaspar** [algolia/algoliasearch-rails#92]
Hey, 

I cannot find a way to do disjunctive faceting.

My current attempt :
  * `Model.search('', {facets: 'stats', facetFilters: "stats:foo,stats:bar"})`
  * `Model.search('', {facets: 'stats', facetFilters: "stats:foo:foo,bar"})`

None of them is returning : `stats:foo OR stats:bar`

How should I do that ?

**Comment by Jerskouille** [comment]
Hi @AlexGaspar ,

Disjunctive faceting is actually a front-end feature only available in our helper ( https://github.com/algolia/algoliasearch-helper-js ) and libraries built on top of it.
The clients are basically a wrapper on the raw API (the `ruby` one at least, the `rails`  one embeds some logic on top of the `ruby` client).

To finally answer your question, I think `Model.search('', {facetFilters: "(stats:foo,stats:bar)"})` should work (if `stats` is declared in your `attributesForFaceting`) (The `facets` parameter is only required to receive the facet values in the response).
However, as you've probably noticed, this is not the way we'd recommend you to use Algolia, to use our service to its full potential we always recommend to use our front-end libraries (mobile or JS).

Let me know how this goes!

**Comment by AlexGaspar** [comment]
Thanks @Jerskouille ! Wrapping it inside parenthesis works! 

We're mainly using Algolia through algoliasearch-helper-js, this is just to handle a very specific case :) 

Thanks again, love the service keep it up !

**Comment by Jerskouille** [comment]
I'm glad I could help you and thanks for your kind words!

**Comment by Genkilabs** [comment]
YES! I needed to do this and have spent hours struggling.

@AlexGaspar Your search engine is great so please, please, please add ruby/rails tabs to your docs so others don't need to struggle to find secrets in threads like this.
I understand that this is not the way you "prefer" people to use your service. But I am not currently permitted to change the front end at all, including adding your javascript, so all I can do is receive params from a post request. After trying every conceivable permutation of "OR" and "disjunctiveFacets" it turns out that params around the filters is the undocumented secret to make it work!

**Comment by Genkilabs** [comment]
For any who arrive here, if you need to "AND" and "OR" facet filters in this manner, you must pass a sting. While ```Model.search('', {facetFilters: ["stats:foo", "stats:bar"]})``` works find for ~"foo AND bar" it turns out that ```Model.search('', {facetFilters: ["stats:foobar", "(stats:foo,stats:bar)"]})``` will not work. Instead pass just a string like ```Model.search('', {facetFilters: "stats:foobar,(stats:foo,stats:bar)"})``` for the ~"foobar AND ( foo OR bar )" effect.

**Comment by Jerskouille** [comment]
Hi @Genkilabs ! You can actually find the whole Ruby documentation [on our website](https://www.algolia.com/doc/api-client/ruby).
For our guides, in a lot of cases, what makes sense in a front-end environment won't in a back-end one, which is why we've restricted our Ruby doc to a full documentation of its methods.

By the way, `facetFilters` are now deprecated for a new parameter called [`filters`](https://www.algolia.com/doc/api-client/ruby/parameters#filters). Its syntax is definitely easier to read.
Your example for instance would become: `stats:foobar AND ( stats:foo OR stats:bar )`.

**Comment by Genkilabs** [comment]
@Jerskouille awesome! thanks for getting back to me on that. I had been linked to your "guides" and was just wasting my effort there when you had robust Ruby API docs around the corner the whole time.
*ashamed* Maybe it was time for a break...
Anyways, this is what I need, thank you.
